name: Build Microzig

on:
  push:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**
  pull_request:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**

jobs:
  build-microzig:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'main' ) || github.ref_name == 'main' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: 0.13.0
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  build-microzig-master:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'zig-master' ) || github.ref_name == 'zig-master' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: master
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  create-branch:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - build-microzig
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: cbe
        name: Check branch exists
        # The list remote returns nothing if the branch does not exist.
        # So, if there is nothing in the command output, it does not exist
        run: |
          if [[ -z "$(git ls-remote --heads origin master-patch/${{ github.sha }})" ]]; then
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "exists=false"
          else
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "exists=true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Vent-Finance/branch_creator@v1.0.0
        if: steps.cbe.outputs.exists == 'false'
        with:
          name: master-patch/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          depth: 0
          ref: zig-master
      - id: cpe
        name: check pr exists
        # github actions pr only outputs when the query find something.
        # So, if the output is empty, pr does not exist
        run: |
          gh pr list -B zig-master -H "master-patch/${{ github.sha }}" 2> check-pr-exists-output
          if [[ -z "$(cat check-pr-exists-output)" ]]; then 
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "exists=false"
          else
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "exists=true"
          fi
          rm check-pr-exists-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create pull request,
        if: steps.cpe.outputs.exists == 'false' && steps.cbe.outputs.exists == 'true'
        run: |
          gh pr create -B zig-master -H master-patch/${{ github.sha }} --title 'Test commit ${{ github.sha }} with zig master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
