name: Build Microzig

on:
  push:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**
  pull_request:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**

jobs:
  build-microzig:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'main' ) || github.ref_name == 'main' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: 0.13.0
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  build-microzig-master:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'zig-master' ) || github.ref_name == 'zig-master' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: master
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  create-branch:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - build-microzig
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check branch exists
        id: check-branch-exists
        run: |
          if [[ -n $(git ls-remote --heads origin master-patch/${{ github.sha }}) ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        if: ${{ ! steps.check-branch-exists.outputs.exists }}
      - uses: Vent-Finance/branch_creator@v1.0.0
        if: ${{ ! steps.check-branch-exists.outputs.exists }}
        with:
          name: master-patch/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          depth: 0
          ref: zig-master
      - name: check pr exists
        run: |
          gh pr list -B zig-master -H master-patch/${{ github.sha }} | grep -q "no pull requests"
      - name: create pull request,
        if: ${{ }}
        run: |
          gh pr create -B zig-master -H master-patch/${{ github.sha }} --title 'Test commit ${{ github.sha }} with zig master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
