name: Build Microzig

on:
  push:
    branches: [main]
    paths:
      - build.zig*
      - tools/**
      - core/**
      - bsp/**
      - examples/**
  pull_request:
    branches: [main]
    paths:
      - build.zig*
      - tools/**
      - core/**
      - bsp/**
      - examples/**

jobs:
  build-microzig:
    uses: ZigEmbeddedGroup/microzig/.github/workflows/build-zig.yml
    with:
      zig-version: 0.13.0
      get-submodules: true
      sparse-checkout-patterns: |
        build.zig*
        tools/**
        core/**
        build/**
        bsp/**
        examples/**
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
