name: Build Microzig

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**
  pull_request:
    branches: [main, zig-master]
    #    paths:
    #      - build.zig*
    #      - tools/**
    #      - core/**
    #      - bsp/**
    #      - examples/**

jobs:
  build-microzig:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'main' ) || github.ref_name == 'main' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: 0.13.0
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  build-microzig-master:
    if: ${{ ( github.event_name == 'pull_request' && github.base_ref == 'zig-master' ) || github.ref_name == 'zig-master' }}
    uses: ./.github/workflows/zig-build-base.yml
    with:
      zig-version: master
      get-submodules: true
      is-packaged: true
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  create-branch:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - build-microzig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Vent-Fiance/branch_creator@v1
        with:
          name: master-patch/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: master-patch/${{ github.sha }}
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: zig-master
