name: Deploy

permissions:
  contents: write

on:
  push:
    tags:
      - "microzig-*.*.*"

jobs:
  build-microzig:
    uses: ./.github/workflows/build-zig-base.yml
    with:
      zig-version: 0.13.0
      get-submodules: true
      sparse-checkout-patterns: |
        build.zig*
        tools/**
        core/**
        build/**
        bsp/**
        examples/**
      is-packaged: true
      github-artifact-name: microzig
      artifact-output-paths: boxzer-out
    secrets:
      downloads-url: ${{ secrets.DOWNLOADS_URL }}
  publish-microzig:
    uses: ./.github/workflows/publish-base.yml
    with:
      tag: ${{ github.ref_name }}
      artifact: microzig
      github-artifact-name: microzig-build
      artifact-target-name: "."
      source: boxzer-out/
    secrets:
      ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      host: ${{ secrets.DEPLOY_HOST }}
      port: ${{ secrets.DEPLOY_PORT }}
      user: ${{ secrets.DEPLOY_USER }}
